// <auto-generated />
namespace WebGarage.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Created_Member_and_VehicleType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Created_Member_and_VehicleType));
        
        string IMigrationMetadata.Id
        {
            get { return "201605240758530_Created_Member_and_VehicleType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
