// <auto-generated />
namespace WebGarage.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Made_relationships_nullable_and_added_size : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Made_relationships_nullable_and_added_size));
        
        string IMigrationMetadata.Id
        {
            get { return "201605240913266_Made_relationships_nullable_and_added_size"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
